# Generated by Django 3.2.3 on 2021-06-07 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('isActive', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumber', models.IntegerField()),
                ('courseName', models.CharField(max_length=200)),
                ('courseDesc', models.CharField(max_length=500)),
                ('host', models.CharField(choices=[('CAL', 'CALUM'), ('YAN', 'YANNA'), ('HAN', 'HANNA'), ('EXT', 'EXTERNAL')], max_length=3)),
                ('min_participants', models.IntegerField()),
                ('max_participants', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('image', models.ImageField(default='course.jpg', upload_to='course_photos')),
                ('course_completed', models.BooleanField(blank=True)),
                ('program', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='booking.programs')),
            ],
        ),
        migrations.CreateModel(
            name='attendees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('UI', 'UX & UI'), ('IT', 'IT & Support'), ('RI', 'Research & Innovation'), ('MD', 'Mobile Development'), ('WD', 'Web Development'), ('CS', 'Cyber Security'), ('HR', 'Human Resources'), ('FN', 'Finance'), ('SA', 'Sales'), ('MA', 'Marketing')], max_length=2)),
                ('course_due', models.CharField(choices=[('W1M', 'Within 1 Month'), ('1-3', '1-3 Months'), ('3-6', '3-6 Months'), ('6+M', '6+ Months')], max_length=3)),
                ('your_development', models.CharField(max_length=3000)),
                ('manager_complete', models.CharField(blank=True, max_length=1000)),
                ('approved', models.BooleanField(blank=True, default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.course')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='AttendManager', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
