# Generated by Django 3.2.3 on 2021-06-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseNumber',
        ),
        migrations.AddField(
            model_name='course',
            name='courseName',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
