# Generated by Django 3.2.3 on 2021-06-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210601_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseDesc',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
