# Generated by Django 3.2.3 on 2021-06-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_course_coursedesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='availablePrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='courseNumber',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
