# Generated by Django 3.2.3 on 2021-06-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210602_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableprograms',
            name='isActive',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
