# Generated by Django 3.2.3 on 2021-06-03 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210602_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableprograms',
            name='isActive',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='booking.availableprograms'),
        ),
    ]
