# Generated by Django 3.2.3 on 2021-06-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20210603_0933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='availablePrograms',
            new_name='Programs',
        ),
    ]
