# Generated by Django 3.2.3 on 2021-06-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_rename_availableprograms_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='course.jpg', upload_to='course_photos'),
        ),
    ]
