# Generated by Django 3.2.3 on 2021-06-04 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0009_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendees',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='attendees',
            name='course_due',
            field=models.CharField(choices=[('W1M', 'Within 1 Month'), ('1-3', '1-3 Months'), ('3-6', '3-6 Months'), ('6+M', '6+ Months')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendees',
            name='department',
            field=models.CharField(choices=[('UI', 'UX & UI'), ('IT', 'IT & Support'), ('RI', 'Research & Innovation'), ('MD', 'Mobile Development'), ('WD', 'Web Development'), ('CS', 'Cyber Security'), ('HR', 'Human Resources'), ('FN', 'Finance'), ('SA', 'Sales'), ('MA', 'Marketing')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendees',
            name='manager',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendees',
            name='manager_complete',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendees',
            name='role',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendees',
            name='your_development',
            field=models.CharField(default=1, max_length=3000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendees',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
