# Generated by Django 3.2.3 on 2021-06-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_availableprograms_isactive'),
        ('booking', '0011_alter_attendees_manager_complete'),
    ]

    operations = [
    ]
