# Generated by Django 3.2.3 on 2021-06-07 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0012_merge_20210607_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendees',
            name='manager_complete',
        ),
        migrations.AlterField(
            model_name='attendees',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='AttendManager', to=settings.AUTH_USER_MODEL),
        ),
    ]
