# Generated by Django 3.2.3 on 2021-06-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20210607_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_completed',
        ),
    ]
