# Generated by Django 3.2.3 on 2021-06-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_remove_course_course_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_completed',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
