# Generated by Django 3.2.3 on 2021-06-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_course_course_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendees',
            name='department',
        ),
    ]
