# Generated by Django 3.2.3 on 2021-06-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_attendees_blankfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendees',
            name='blankField',
        ),
    ]
