# Generated by Django 3.2.3 on 2021-06-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_remove_attendees_blankfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendees',
            name='manager',
        ),
    ]
