# Generated by Django 3.2.3 on 2021-06-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_remove_attendees_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendees',
            name='approved',
        ),
        migrations.AddField(
            model_name='attendees',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('APR', 'Approved'), ('REJ', 'Rejected')], default='PEN', max_length=3),
        ),
    ]
