# Generated by Django 3.2.3 on 2021-06-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_auto_20210610_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='division_access',
            field=models.CharField(choices=[('GLO', 'Company Wide'), ('OPE', 'Operations'), ('TEC', 'Technology'), ('FIN', 'Finance'), ('MAR', 'Marketing')], default='GLO', max_length=3),
        ),
    ]
