# Generated by Django 3.2.3 on 2021-06-07 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='manager',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='auth.user'),
            preserve_default=False,
        ),
    ]
