# Generated by Django 3.2.3 on 2021-06-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='division',
            field=models.CharField(choices=[('OPE', 'Operations'), ('TEC', 'Technology'), ('FIN', 'Finance'), ('MAR', 'Marketing')], default='OPE', max_length=3),
        ),
    ]
